### PR TITLE
Add Feature Youtube Clone

### PR DESCRIPTION
**Pull request by Bluette1**
- Add Feature Youtube Clone

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your did a good job so far :+1:
### Here some things you need to understand about submitting pull request:
* No need to create new Pull request when you submit project for rereview. Just push new changes and submit link to the same pull request.
* You should not merge to master until TSE approves Pull request.
### Here things you need to fix before this project can be approved:
* [ ] Navigation bar should have a `<button>` tag that represents the search button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/search_button_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))Right now you have just icon, that should be changed.
* [ ] Project should have a share button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)) Right now you have span, that should be changed.

[OPTIONAL]
* It's a good practice to use the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links.
### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by fatymahmed — APPROVED** [review]
Hi @Bluette1 @kelibst 
Your project looks good👏👏
Congratulations on completing the project.
## Status: Approved
_You may go ahead and merge your pull request and don't forget to fill your project completion form_

**Comment by Bluette1** [comment]
@fatymahmed Okay. Thank you very much!!

**Pull request merged**
